@baseURL = http://localhost:3333

# @name create_account
POST {{baseURL}}/accounts
Content-Type: application/json

{
  "name": "Yale Henrique",
  "email": "yale850@gmail.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseURL}}/sessions
Content-Type: application/json

{
  "email": "yale850@gmail.com",
  "password": "123456"
}