@baseURL = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseURL}}/accounts
Content-Type: application/json

{
  "name": "Yale Henrique",
  "email": "yale850@gmail.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseURL}}/sessions
Content-Type: application/json

{
  "email": "yale850@gmail.com",
  "password": "123456"
}

###

# @name create_question
POST {{baseURL}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Terceira pergunta",
  "content": "Conteúdo da terceira pergunta"
}

###

# @name fetch_recent_questions
GET {{baseURL}}/questions?page=2
Authorization: Bearer {{authToken}}
